export const MAIN_FLOW_INIT = 'MAIN_FLOW_INIT';
export const MAIN_FLOW_START = 'MAIN_FLOW_START';
export const MAIN_FLOW_AVOID_CONFLICT = 'MAIN_FLOW_AVOID_CONFLICT';

export const MAP_1_INIT = 'MAP_1_INIT';
export const MAP_1_START = 'MAP_1_START';

export const COMMON_MAP_INIT = 'COMMON_MAP_INIT';
export const COMMON_MAP_START = 'COMMON_MAP_START';
export const COMMON_MAP_CHECK_MAP_SITUATION = 'COMMON_MAP_CHECK_MAP_SITUATION';
export const COMMON_MAP_MOVE_TO_FLAG = 'COMMON_MAP_MOVE_TO_FLAG';
export const COMMON_MAP_MOVE_TO_ENEMY = 'COMMON_MAP_MOVE_TO_ENEMY';
export const COMMON_MAP_MOVE_TO_CENTER = 'COMMON_MAP_MOVE_TO_CENTER';
export const COMMON_MAP_AUTO_FIRE = 'COMMON_MAP_AUTO_FIRE';
export const COMMON_MAP_DODGE_BULLET = 'COMMON_MAP_DODGE_BULLET';
